run:
  timeout: 5m

linters:
  disable-all: true
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - unused
    - unconvert
    - goconst
    - misspell
    - unparam
    - prealloc
    - exportloopref
    - gochecknoinits
    - gocritic
    - dupl
    - gocyclo
    - goimports
    - ineffassign
  fast: false

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck