server:
  host: "localhost"
  port: 8080

database:
  dsn: user=postgres password=password host=postgres port=5432 dbname=merch-shop sslmode=disable pool_max_conns=10

log:
  level: "debug"
  output: "logs/app.log"
